[project]
name = "crud-flask"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dart-sass>=0.5.2",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
]
