[project]
name = "crud-flask"
version = "1.0.5"
description = "CRUD Task List"
requires-python = ">=3.13"
dependencies = [
    "dart-sass>=0.5.2",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "python-dotenv>=1.1.1",
]
